pool:
  vmImage: 'macOS-10.15'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 14.x
  - script: npm install
    displayName: Install & Build
    env:
      JAVA_HOME: $(JAVA_HOME_11_X64)
      PATH: $(JAVA_HOME_11_X64)/bin:$(PATH)
