# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'macOS-10.15'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 12.x
  - script: npm install
    displayName: Install Node dependencies
  - script: npm run build
    displayName: Building the app
