language: android
jdk: oraclejdk8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
android:
  components:
    - platform-tools
    - tools
    - build-tools
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
env:
  global:
    - DEVICE=android
    - BUILD_TOOLS=28.0.3
    - API_TARGET=android-28
    - CC=gcc-6 CXX=g++-6
before_install:
  - echo $ANDROID_HOME
  - echo yes | android update sdk --no-ui -t tools
  - echo yes | sdkmanager --update > /dev/null
  - echo yes | sdkmanager "build-tools;${BUILD_TOOLS}" >/dev/null
  - echo yes | sdkmanager "platforms;${API_TARGET}" >/dev/null
  - sdkmanager --list
install:
  - nvm install 10
  - npm install
script:
  - npm run build
